import {createRoot} from 'react-dom/client';
import {flushSync} from 'react-dom';
import {createTextStream,StreamingText,durations,type StreamSession} from '../src/index';
import {readMockStream} from '../demo/protocol';
import '../src/style.css';
import {runSmoothingChecks} from './smoothing-browser-checks';
const fixture=document.getElementById('fixture')!;
const root=createRoot(fixture);
const results:{name:string;passed:boolean;detail?:unknown}[]=[];
const assert=(condition:unknown,message:string)=>{if(!condition)throw new Error(message);};
const delay=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms));
async function until(predicate:()=>boolean){const start=performance.now();while(!predicate()){if(performance.now()-start>4000)throw new Error('Timed out');await delay(16);}}
function mount(){const stream=createTextStream();const session=stream.begin();flushSync(()=>root.render(<StreamingText stream={stream} session={session}/>));return {stream,session};}
async function transport(s:StreamSession,scenario:string,signal?:AbortSignal){s.requestStarted();try{await readMockStream(await fetch('/api/mock',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({scenario}),signal}),e=>{if(e.type==='text')s.append(e.text);else s.complete();});}catch(error){if(signal?.aborted)s.interrupt();else s.fail(error);}}
async function check(name:string,body:()=>Promise<unknown>){try{const detail=await body();results.push({name,passed:true,detail});}catch(e){results.push({name,passed:false,detail:String(e)});}}
document.getElementById('run')!.addEventListener('click',async()=>{
 results.length=0;(document.getElementById('run') as HTMLButtonElement).disabled=true;document.getElementById('status')!.textContent='Running';
 await check('first incomplete sentence appears before stream completion',async()=>{const f=mount();const task=transport(f.session,'normal');await until(()=>fixture.textContent?.includes('You can start reading')===true);assert(!fixture.textContent?.includes('finished'),'first fragment was buffered');assert(f.stream.getSnapshot().status==='streaming','stream finished too soon');await until(()=>f.stream.getSnapshot().marks.firstVisibleAt!==null);const node=fixture.querySelector('.stream-readable')!.firstChild;await task;assert(fixture.querySelector('.stream-readable')!.firstChild===node,'old text node remounted');return durations(f.stream.getSnapshot().marks);});
 await check('1,000-fragment HTTP burst loses no text',async()=>{const f=mount();await transport(f.session,'burst');await until(()=>fixture.textContent===f.stream.getSnapshot().text);assert(f.stream.getSnapshot().text==='You can start reading'+' x'.repeat(1000),'lost or reordered fragments');assert(f.stream.getSnapshot().fragments===1001,'wrong count');assert(f.stream.getSnapshot().publications<1001,'no batching');return {fragments:1001,publications:f.stream.getSnapshot().publications};});
 await check('abort before first text stays empty',async()=>{const f=mount();const abort=new AbortController();const task=transport(f.session,'normal',abort.signal);await delay(50);abort.abort();await task;assert(f.stream.getSnapshot().status==='interrupted','wrong status');assert(f.stream.getSnapshot().text==='','received unexpected text');assert(f.stream.getSnapshot().marks.firstTextAt===null,'fabricated arrival');});
 await check('interrupt preserves already received partial text',async()=>{const f=mount();const abort=new AbortController();const task=transport(f.session,'normal',abort.signal);await until(()=>f.stream.getSnapshot().text.length>0);abort.abort();await task;const partial=f.stream.getSnapshot().text;await delay(250);assert(f.stream.getSnapshot().text===partial,'late text after stop');assert(f.stream.getSnapshot().status==='interrupted','wrong status');});
 await check('restart isolates stale transport callbacks',async()=>{const f=mount();const old=transport(f.session,'normal');await delay(40);const fresh=f.stream.begin();fresh.requestStarted();flushSync(()=>root.render(<StreamingText stream={f.stream} session={fresh}/>));fresh.append('New session');fresh.complete();await old;assert(f.stream.getSnapshot().text==='New session','old transport contaminated restart');});
 await check('transport error keeps partial text and reports failure',async()=>{const f=mount();await transport(f.session,'error');assert(f.stream.getSnapshot().status==='error','wrong status');assert(f.stream.getSnapshot().error==='Synthetic transport failure','missing error');assert(f.stream.getSnapshot().text.includes('You can start reading'),'partial text lost');});
 await check('HTML-shaped text is rendered as text',async()=>{const f=mount();f.session.requestStarted();f.session.append('<img src=x onerror=alert(1)>');f.session.complete();await until(()=>fixture.textContent?.includes('<img')===true);assert(!fixture.querySelector('img'),'unsafe HTML injection');});
 await check('content has no animation and remains fully opaque',async()=>{const el=fixture.querySelector('.stream-readable')!;const style=getComputedStyle(el);assert(style.animationName==='none','content animation');assert(style.opacity==='1','hidden content');assert(style.transform==='none','translated content');assert(style.transitionDuration==='0s','content transition');return {reducedMotion:matchMedia('(prefers-reduced-motion: reduce)').matches,animation:style.animationName,opacity:style.opacity};});
 results.push(...await runSmoothingChecks(root,fixture));
 document.getElementById('results')!.textContent=JSON.stringify({userAgent:navigator.userAgent,viewport:{width:innerWidth,height:innerHeight},reducedMotion:matchMedia('(prefers-reduced-motion: reduce)').matches,passed:results.filter(r=>r.passed).length,total:results.length,results},null,2);
 document.getElementById('status')!.textContent=results.every(r=>r.passed)?'PASS':'FAIL';(document.getElementById('run') as HTMLButtonElement).disabled=false;
});
